# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c992dc2781c5f636579923238eec080eee0c3be46ee6b1c85fd0b7283e2e4b7f1bdbf0d98833bc18f33c9914da62f789a478ce382742943dfef03b1b3903be4

test:
  secret_key_base: 556e02bc0e7584185f0033ef03eb50511ddc9870d0c67ab884520e45cbfc905ae54674269701b72485c6a9393a1883c88ab745fb97f1e138b080c5f434577678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
